### ISSUE TITLE
Code shown in Report does not define "params" 

### ISSUE THREAD

**Issue by smoe** [BIMSBbioinfo/pigx_rnaseq#115]
To elucidate why the g:profiler results don't show in my hisat2 analysis' report, I thought I should execute the corresponding code prior to creating this issue. However, variables are missing which I presume to be defined somewhere in the code blocks above. The top code block however starts with
```
countDataFile <- params$countDataFile
colDataFile <- params$colDataFile
gtfFile <- params$gtfFile
caseSampleGroups <- params$caseSampleGroups
controlSampleGroups <- params$controlSampleGroups
covariates <- params$covariates
prefix <- params$prefix
workdir <- params$workdir
```
which likely refers to the settings.yaml, but the code how to read that is not shown.

**Comment by borauyar** [comment]
#116 by @smoe improves the report output for debugging purposes.
