### ISSUE TITLE
Outdated m4/ax_r_package.m4

### ISSUE THREAD

**Issue by tillea** [BIMSBbioinfo/pigx_rnaseq#125]
Hi,
as reported in a [Debian bug report](https://bugs.debian.org/1008368) detecting R packages fails.  I was able to cure this by simply using the Debian packaged version of this M4 macro script.  I'd recommend to pick a newer version from wherever you got it.  If you want to fix it this should be possible by adding two "tostring" functions in the comparison statements when querying for the R packages.
Kind regards, Andreas.

**Comment by rekado** [comment]
Thanks, fixed.
