### ISSUE TITLE
suggesting singularity image

### ISSUE THREAD

**Issue by smoe** [BIMSBbioinfo/pigx_rnaseq#127]
I need to bring pigx-rnaseq to our HPC environment and, well, guix is not much better available than a Debian package since that old CentOS environment is a bit tricky.

What came to mind was to use [Singularity](https://en.wikipedia.org/wiki/Singularity_(software)) - this issue could possibly collect all the requests for such an image.

**Comment by rekado** [comment]
We can build a Singularity image with `guix pack -f squashfs`.

**Comment by rekado** [comment]
If you don't have Singularity on the HPC cluster you could also use `guix pack -RR` to build a self-contained, portable tarball that can be unpacked anywhere.  `guix pack` includes various backends that might work even on older HPC systems: https://hpc.guix.info/blog/2020/05/faster-relocatable-packs-with-fakechroot/

**Comment by smoe** [comment]
Both options read very nice. I think I want to try both. Many thanks! Should have proposed this earlier :)
