### ISSUE TITLE
error when executing

### ISSUE THREAD

**Issue by Pinolinoo** [BIMSBbioinfo/pigx_rnaseq#132]
Hi, I have issues running the pigx-rnaseq -s command. 

it tells me: 
```
Traceback (most recent call last):
  File "/home/proth/.guix-profile/bin/pigx-rnaseq", line 486, in <module>
    generate_config(args.configfile,
  File "/home/proth/.guix-profile/bin/pigx-rnaseq", line 236, in generate_config
    update_config(settings,yaml.safe_load(open(settingsfile, 'r')))
  File "/gnu/store/8kha44h8bvx8y8a2aphl0mygwflmqa51-snakemake-5.32.2/lib/python3.9/site-packages/snakemake/utils.py", line 480, in update_config
    _update(config, overwrite_config)
  File "/gnu/store/8kha44h8bvx8y8a2aphl0mygwflmqa51-snakemake-5.32.2/lib/python3.9/site-packages/snakemake/utils.py", line 473, in _update
    for (key, value) in u.items():
```

best 
philipp

**Comment by borauyar** [comment]
Hi Philipp,
Looks like something is wrong with the content of the settings file. 
Did you modify the content of the settings file that is generated with `--init`? 

Can you please provide a settings.yaml file that we can use to test if we can reproduce the error?

**Comment by Pinolinoo** [comment]
I did change the input dirs and also deleted some lines in the DE analysis section since I only wanted to do one comparison! 

here's the settings file.

`I# locations:
#   reads-dir: /fast/AG_Metzger/philipp/raw_data/HD/short_reads_3d/all_reads/
#   output-dir: /fast/AG_Metzger/philipp/results/pigx/RNA-Seq/HD_organoids/output/
#   genome-fasta: /fast/AG_Metzger/philipp/raw_data/genome_files.fa
#   cdna-fasta: /fast/AG_Metzger/philipp/raw_data/genome_files/Homo_sapiens.GRCh38.cdna.all.fa
#   gtf-file: /fast/AG_Metzger/philipp/raw_data/genome_files/hg38.gtf
# 
# # The "organism" field is needed for GO term analysis. Leave it empty
# # if not interested in GO analysis.  Otherwise provide a string with
# # the initial of genus and the species name (e.g. hsapiens, mmusculus,
# # dmelanogaster, celegans)
# organism: 'hsapiens'
# 
# mapping:
#   mapper: 'hisat2' # options are star or hisat2
#   genome_build: 'GRCm38'  #genome build version identifier that is used in hisat2 index file names
# 
# coverage:
#   tool: 'megadepth' # options are megadepth or bamCoverage 
# 
# # Configuration for how to do read counting using
# # GenomicAlignments::summarizeOverlaps feature type and grouping
# # features must match what is available in the GTF file most GTF files
# # will use "exon" or "CDS" as features and "gene_id", and
# # "transcript_id" for combining features.
# counting:
#   counting_mode: "Union" # other options are "IntersectionStrict" and "IntersectionNotEmpty"
#   drop_nonunique: TRUE # boolean, When set to TRUE, multi-mapping reads are not counted (see inter.feature argument of summarizeOverlaps)
#   strandedness: "unspecific" # other options are "forward" and "reverse" for strand-specific read-counting
#   feature: "exon"
#   group_feature_by: "gene_id"
#   yield_size: 2000000 # how many reads to process at a time (this impacts memory consumption)
# 
# #DEanalyses:
# #  # The names of analyses can be anything but they have to be unique
# #  # for each combination of case control group comparisons.
# #  # Every analysis also needs a covariates line with a quoted character
# #  # string value.
# #
# #  analysis1:
# #    description: "A couple of sentences describing the purpose to perform this particular comparison and the selection of covariates."
# #    # If multiple sample names are provided, they must be separated by comma.
# #    case_sample_groups: "306"
# #    control_sample_groups: "JG"
# #
# #    # comma separated list of additional co-variates to control for
# #    # in differential expression analysis (e.g. batch, age,
# #    # temperature, sequencing_technology etc.). Must correspond to a
# #    # column field in the sample_sheet.csv file.)
# #    covariates: ""
# execution:
#   submit-to-cluster: yes
#   jobs: 40
#   nice: 19
#   mem_mb: 64000
#   cluster:
#     missing-file-timeout: 120
#     memory: 8G
#     stack: 128M
#     queue: all.q
#     contact-email: none
#     log-dir: '.'
#     args: ''
#   rules:
#     __default__:
#       threads: 1
#       memory: 2000
#     translate_sample_sheet_for_report:
#       threads: 1
#       memory: 500
#     trim_qc_reads:
#       threads: 1
#       memory: 4000
#     star_index:
#       threads: 2
#       memory: 32000
#     hisat2-build:
#       threads: 2 
#       memory: 32000
#     salmon_index:
#       threads: 8
#       memory: 5000
#     salmon_quant:
#       threads: 8
#       memory: 6000
#     counts_from_salmon: 
#       threads: 1
#       memory: 200
#     collate_read_counts:
#       threads: 1
#       memory: 200
#     norm_counts_deseq:
#       threads: 1
#       memory: 1000 
#     star_map:
#       threads: 2
#       memory: 16000
#     hisat2:
#       threads: 2
#       memory: 8000
#     index_bam:
#       threads: 2
#       memory: 500
#     multiqc:
#       threads: 2
#       memory: 500
#     coverage_bamCoverage:
#       threads: 1
#       memory: 4000
#     coverage_megadepth:
#       threads: 2
#       memory: 4000
#     count_reads:
#       threads: 1
#       memory: 6000
#     check_annotation_files: 
#       threads: 1
#       memory: 16000
#     reports:
#       threads: 1
#       memory: 4000  
# 
# tools:
#   gunzip:
#     executable: /gnu/store/0c1yfbxyv877mlgychfgvmk5ha2jqh52-gzip-1.10/bin/gunzip
#     args: ""
#   multiqc:
#     executable: /gnu/store/j9nv42q9jgfnzxdn5knd04bww7v9nvhh-multiqc-1.10.1/bin/multiqc
#     args: ""
#   star_map:
#     executable: /gnu/store/h249giysr758g9776dwwmql5sb4wkcrv-star-2.7.3a/bin/STAR
#     args: ""
#   star_index:
#     executable: /gnu/store/h249giysr758g9776dwwmql5sb4wkcrv-star-2.7.3a/bin/STAR
#     args: ""
#     # If STAR gives an error then that error message is likely suggest the parameter to adjust.
#     # args: "--limitGenomeGenerateRAM 31000000000"
#   hisat2:
#     executable: /gnu/store/k2fwdwfp75nhnkf162f9nrxd0cyjjp4x-hisat2-2.2.1/bin/hisat2
#     args: "--fast" 
#     # If low alignment rates are observed with "--fast" setting, 
#     # other options to try are "--sensitive or --very-sensitive". 
#   hisat2-build:
#     executable: /gnu/store/k2fwdwfp75nhnkf162f9nrxd0cyjjp4x-hisat2-2.2.1/bin/hisat2-build
#     args: ""
#   samtools:
#     executable: /gnu/store/02ys56mlshjwh4y5ziflpf9586wh1sn4-samtools-1.14/bin/samtools
#     args: ""
#   salmon_index:
#     executable: /gnu/store/a1h3rwvs3lnd90zl75jm0bpnzkl3zjp6-salmon-1.6.0/bin/salmon
#     args: "index"
#   salmon_quant:
#     executable: /gnu/store/a1h3rwvs3lnd90zl75jm0bpnzkl3zjp6-salmon-1.6.0/bin/salmon
#     args: "quant"
#   Rscript:
#     executable: /gnu/store/zwlc915dpafababhm9wjfbdla919zvxm-r-minimal-4.2.1/bin/Rscript
#     args: "--vanilla"
#   sed:
#     executable: /gnu/store/zhd6blbfz40xp62i4d1rcgbyrpkynbkc-sed-4.8/bin/sed
#     args: ""
#   fastp:
#     executable: /gnu/store/57rv4nz7fzi3dw4khzl30338l9pi5zvc-fastp-0.20.1/bin/fastp
#     args: "--adapter_sequence=AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" 
#     # Please refer to fastp manual about setting adapter sequences: https://github.com/OpenGene/fastp#adapters
#   bamCoverage:
#     executable: /gnu/store/klfsrmmp6ksd835grhhb9571zyw4vcm1-python-deeptools-3.4.3/bin/bamCoverage
#     args: "--normalizeUsing BPM --numberOfProcessors 2" 
#     # see https://deeptools.readthedocs.io/en/develop/content/tools/bamCoverage.html
#     # for more detailed arguments used for normalising coverage data files
#   megadepth:
#     executable: /gnu/store/s36wj19iypzd7b579h0vz9a48iiynyqr-megadepth-1.1.1/bin/megadepth
#     args: ""
#  
`

**Comment by Pinolinoo** [comment]
Ok solved it, I didn't know I had to delete the # in the init settings files but found out after comparing to the test_data settings file! :) 
Kinda stupid of me :D but thanks!

**Comment by borauyar** [comment]
Okay great! 
That is a common mistake, I guess we should improve our documentation :)
