### ISSUE TITLE
Fix mismatching names for cluster config and Snakefile

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_rnaseq#138]
See https://github.com/BIMSBbioinfo/pigx_rnaseq/issues/128#issuecomment-2034898830

- [x] hisat2-build -->  hisat2_index 

https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/bd38e02d499fa93ef44f95aaf3b5c4c8c636a19c/snakefile.py#L356-L363

https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/bd38e02d499fa93ef44f95aaf3b5c4c8c636a19c/etc/settings.yaml.in#L94

**Comment by alexg9010** [comment]
- [ ] trim_qc_reads --> trim_qc_reads_pe, trim_qc_reads_se

https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/bd38e02d499fa93ef44f95aaf3b5c4c8c636a19c/snakefile.py#L318-L341

https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/bd38e02d499fa93ef44f95aaf3b5c4c8c636a19c/etc/settings.yaml.in#L88

**Comment by alexg9010** [comment]
- [ ] hisat2 --> hisat2_map

https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/bd38e02d499fa93ef44f95aaf3b5c4c8c636a19c/snakefile.py#L402-L409

https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/bd38e02d499fa93ef44f95aaf3b5c4c8c636a19c/etc/settings.yaml.in#L115

**Comment by alexg9010** [comment]
- [ ] counts_from_SALMON --> counts_from_salmon


https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/bd38e02d499fa93ef44f95aaf3b5c4c8c636a19c/snakefile.py#L468-L479

https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/bd38e02d499fa93ef44f95aaf3b5c4c8c636a19c/etc/settings.yaml.in#L103

**Comment by borauyar** [comment]
@alexg9010 would you like to fix the issue and send a pull request?

**Comment by alexg9010** [comment]
> @alexg9010 would you like to fix the issue and send a pull request?

Just finishing up the collection.
