### ISSUE TITLE
Star Map crashed

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_rnaseq#21]
This occured during one run of star_map, the input file was paired end, with 1.5GB and 1.6GB size for read1 and 2 respectively. 
Aligned against ce11 genome.   

```
Mar 07 16:06:39 ..... started STAR run
Mar 07 16:06:39 ..... loading genome
Mar 07 16:07:07 ..... started mapping

EXITING because of fatal error: buffer size for SJ output is too small
Solution: increase input parameter --limitOutSJcollapsed

Mar 07 16:19:39 ...... FATAL ERROR, exiting
```

**Comment by rekado** [comment]
FWIW I have updated STAR to the latest release (2.5.4b).  Do you see the same error with that version?

**Comment by jonathanronen** [comment]
@borauyar do you know if the celegans genome needs a different `--limitOutSJcollapsed` default?

**Comment by borauyar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [star map crashed](https://trello.com/c/Ln1J9rnJ/27-star-map-crashed)

**Comment by rekado** [comment]
@alexg9010 Is this still a problem with the current version?

**Comment by alexg9010** [comment]
I needed to adjust a certain parameter to get it running, but then it worked.
