### ISSUE TITLE
allow spaces in sample names?

### ISSUE THREAD

**Issue by jonathanronen** [BIMSBbioinfo/pigx_rnaseq#23]
These lines
https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/master/scripts/deseqReport.Rmd.in#L138-L139
remove spaces from sample names.

I assume this was done to trim leading/trailing whitespace, @borauyar ?
If so, I suggest we trim using something like

```r
gsub("^\\s+|\\s+$", "", x)
```

and not

```r
gsub(' ', '', x)
```

as the former only removes whitespace from the head and tail of the string, and the latter (current implementation) removes spaces from inside the string too.

Or perhaps there is a different reason for this being there?
Or perhaps we should leave it as is, which means spaces are not allowed in sample types and covariates?

**Comment by borauyar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [allow spaces in sample names](https://trello.com/c/VQTINJPT/25-allow-spaces-in-sample-names)

**Comment by borauyar** [comment]
https://github.com/BIMSBbioinfo/pigx_rnaseq/issues/56
