### ISSUE TITLE
Add Genome Browser Tracks

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_rnaseq#25]
Is it possible to generate some coverage BigWig Tracks for visualization?

**Comment by jonathanronen** [comment]
pigx_rnaseq outputs bedGraph files. are bigwig's necessary in addition?

**Comment by alexg9010** [comment]
Actually good that you are mentioning, I realized that I did not run the pipeline through yet. 

In general If you are using bedgraph files somewhere downstream, than I am fine with them, 
but if they are only for visualization I would argue that BigWig is more appropriate due to smaller size and streaming.

**Comment by Nicolai-vKuegelgen** [comment]
The bedgraph files that the pipeline currently outputs are based on the reads for both reverse and forward strand. I think in most cases it's better to have tracks that allow to distinguish between these tow, so maybe that could also be added/changed.

**Comment by borauyar** [comment]
We are planning to produce strand specific bigwig files. It is in our to-do list :)

**Comment by borauyar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Genome Browser Tracks](https://trello.com/c/v7iVCYtU/19-add-genome-browser-tracks)

**Comment by Nicolai-vKuegelgen** [comment]
I just saw that (at least the newest version of) STAR can directly output bedgraph or wiggle tracks in both Stranded and unstranded format (options --outWigType and --outWigStrand)

**Comment by borauyar** [comment]
https://github.com/BIMSBbioinfo/pigx_rnaseq/commit/fb8d84b94c9cfcf9b64f458a2fc87cbb0a3806ac
