### ISSUE TITLE
fastqc error on max-cluster

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_rnaseq#26]
Somehow this only happens on max-cluster, either interactive or via qsub.
```
[agosdsc@max075.mdc-berlin.net:~/projects/andreas_atac] $ fastqc --outdir /home/agosdsc/projects/andreas_atac/ --extract -f fastq -t 1 /scratch/AG_Akalin/agosdsc/projects/andreas_rnaseq/fastq/AO_BT_012_S7_L003_R1_001.fastq.gz
Started analysis of AO_BT_012_S7_L003_R1_001.fastq.gz
library initialization failed - unable to get max # of allocated fds
```

**Comment by alexg9010** [comment]
Okay this seems to be the version of fastqc that comes with guixr-rhel6. 
if I use another fastqc, that was linked before, then it works.

**Comment by alexg9010** [comment]
This only happens on max-cluster, on beast it is fine.

@rekado I hope you have an idea.

**Comment by alexg9010** [comment]
this specific version of fastqc does not work: `/gnu/store/4fgppzi48j3c1cwvgp5yd4gs8j63yn0d-fastqc-0.11.5/bin/fastqc`

**Comment by rekado** [comment]
The difference between this and the previous versions of fastqc you may have had is that this one is built completely from source.

We're using fastqc in all of the pipelines.  Are the test results of these pipelines correct?  The tests for all pipelines pass.  Please consider updating the tests to catch this if this is a general problem.

**Comment by rekado** [comment]
On second thought: this looks like a problem in initialising the JVM.  It's possible that this is a problem with running Java on the cluster, not specifically with FastQC.

**Comment by alexg9010** [comment]
The problem is that this particular version runs on beast without problems, but somehow on the max-cluster it does not.
Are there any envirnmental java flags that restrict the memory?

**Comment by rekado** [comment]
This error is about file descriptors, not memory.  The number of open file descriptors is limited on a system.  Maybe try a different node?

**Comment by alexg9010** [comment]
which one for instance? 
until now I tried 2 and both failed.

**Comment by borauyar** [comment]
@rekado has this issue been solved with the latest update?

**Comment by rekado** [comment]
yes, it's fine with Guix from `core-updates` or `rhel6`, and it is only a problem on RHEL6 systems.  `core-updates` will be merged into `master` soon.
