### ISSUE TITLE
bam index should have suffix .bam.bai, not only .bai

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_rnaseq#29]
https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/a366b74f1a1c07ec78e25483230c40fac4a82f50/pigx_rnaseq.py#L330

**Comment by borauyar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bam index should have suffix .bam.bai, not only .bai](https://trello.com/c/A4kvBW9J/22-bam-index-should-have-suffix-bambai-not-only-bai)
