### ISSUE TITLE
etc/settings.yaml.in needs to include default for cdna-fasta

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/pigx_rnaseq#30]
etc/settings.yaml.in needs to include default for cdna-fasta; it doesn't.

**Comment by borauyar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [etc/settings.yaml.in needs to include default for cdna-fasta](https://trello.com/c/MabK0pWV/21-etc-settingsyamlin-needs-to-include-default-for-cdna-fasta)
