### ISSUE TITLE
DESeq result table headers

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [BIMSBbioinfo/pigx_rnaseq#32]
The {sample}.deseq_result.tsv tables have a minor error in the header: 

baseMean | log2FoldChange | lfcSE | stat | pvalue | padj | geneName |  
-- | -- | -- | -- | -- | -- | -- | --
ENSMUST00000170241.7 | 1079.6198652353 | 6.724065275 | 0.2811070578 | 23.9199446937 | 1.90E-126 | 1.36E-121 | NA

The gene/transcript ID column (probably used as row-index internally?) doesn't get a name which shifts the header for the other columns.

**Comment by borauyar** [comment]
Hi Nicolai,

This is not an error. This table can be read into a data frame using the default settings of `read.table` function from the base `utils` library:

You can read it via:
`df <- utils::read.table(<filepath>)`
