### ISSUE TITLE
Putting fastq files in a subfolder leads to filepath/name problems later on

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [BIMSBbioinfo/pigx_rnaseq#33]
If the pipeline starts with some or all fastq files in a subfolder relative to the default location (e.g. fastq/XXX/file.fastq.gz) and this is accordingly noted in the sample sheet it causes a Problem in the Trim_Galore rule: while the trim_galore program itself get the correct input and runs finde the chained renaming of the files (mv {params.tmp} {output}) fails since it assumed that the trimmed files still have the subfolder in the filenames (which is not the case).

It's probably not necessary to allow subfolders for fastq input files, so the easiest solution might be to add a repsective check to the input validation.

And if anyone wonders how this came up:
The demultiplexing program (bcl2fastq) splits the generated fastq files into subfolders if different sample_projects are definded in the Illumina samplesheet.

**Comment by borauyar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [allow fastq files in sub-folders](https://trello.com/c/hkyzJs0Z/31-allow-fastq-files-in-sub-folders)

**Comment by Nicolai-vKuegelgen** [comment]
I found another issue with the fastq files:

If you try to run the pipeline with unzipped files, then it will crash directly after running trim_galore because the renaming command part of that rule assumes that all files are zipped (while trim_galore can work ununzipped files, but will then also output unzipped files).

**Comment by borauyar** [comment]
#56
