### ISSUE TITLE
STAR based counts are always strand-unspecific

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [BIMSBbioinfo/pigx_rnaseq#34]
The summarized table of STAR based gene counts (which is then also the basis for STAR based DEseq) contains only strand-unspecific gene counts:

STAR gives a table with 3 different columns: unstranded-counts, strand-specfic-counts, reverse-stranded counts (according to: https://www.biostars.org/p/218995/ I couldn't find that section in the latest manual)

The R function in the pipeline always takes the second column:
readsmatrix[,i] = readspergene[[i]]$V2

It might be a good if its possible to specify whether reads should be strand-specific in the settings file.

**Comment by borauyar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [STAR based counts are always strand-unspecific](https://trello.com/c/X1voS4UB/36-star-based-counts-are-always-strand-unspecific)
