### ISSUE TITLE
Combined (DEseq) results

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [BIMSBbioinfo/pigx_rnaseq#37]
I think it would be nice to generate one combined output table for all DEseq results (and was already asked to make that for my lab).

I now have an R script that generates one combined output table with:
 - collected DEseq results (containing the most important DEseq columns)
 - marked significantly up- or down-regulated genes for each DEseq analysis
 - additional gene annotation from biomaRt
 - Genes marked, if they belong to one of the top20 groups from GOanalysis

If you would like to adopt this for the pipeline I can give you a file, a few other things I think should also be included in that case are:
- customisable thresholds for p-value & log2fc cutoffs
- export of GOanalysis results, so they don't have to be rerun in this step
- potentially further options to define the top groups for GO analysis (min/max group size etc)

**Comment by borauyar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Combine DESeq result tables into one](https://trello.com/c/kOyHlCeS/72-combine-deseq-result-tables-into-one)

**Comment by FrancescoSantini** [comment]
This commit [here](bd38e02d499fa93ef44f95aaf3b5c4c8c636a19c) fixes this particular request.
Regards
