### ISSUE TITLE
GO analysis report

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [BIMSBbioinfo/pigx_rnaseq#38]
The GO-term anaylsis table in the in the DEseq report tables puts together all of the gprofiler output, which has some problems:

The gProfiler package doesn't only analyse for matches in the GO database but also others (e.g. transcription-factor binding sites). All these results are mixed together and in some cases (especially the TF sites) don't make sense for RNAseq data in the first place. While its still possible to look only at results for specific databases (like GO Biological Processes), the column that allows differentiation of these databases is hidden by default (so people won't even see what they're looking at initially).

I think the table could be improved a lot if:
 - the domain column was visible by default
 - results are sorted by pvalue & domain
 - irrelevant databases (TF) are removed from the results

**Comment by borauyar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [improve GO analysis presentation in report](https://trello.com/c/8a8VTw58/71-improve-go-analysis-presentation-in-report)
