### ISSUE TITLE
Rule all / 'final-report' doesn't include STAR counts

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [BIMSBbioinfo/pigx_rnaseq#43]
The "rule all" with the default 'final target' does not specifically include the STAR count table (preprocessed_data/counts_from_STAR.tsv generated by the "counts_from_STAR" rule).
This means that if the pipeline is run without any DEseq analysis the count_table from STAR will not be generated since it's currently only used as an intermediate step for the DEseq reports.

I think it would be better to include this table in the final target (like the salmon counts which are already included there).

**Comment by borauyar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rule all / 'final-report' doesn't include STAR counts](https://trello.com/c/HMXBgq7w/82-rule-all-final-report-doesnt-include-star-counts)
