### ISSUE TITLE
Interactive plot and GO results are blank (R 3.5)

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [BIMSBbioinfo/pigx_rnaseq#45]
After updating the pipeline I noticed that the interactive volcano plot and GO results sections (5.3. & 6) in the html reports show up blank. I've also run the newest version of the pipeline in a 'clean' environment without any other R installations to make sure this isn't cause by some external interactions.

For the interactive plot there is some blank space, so it seems that the printing happens but not properly, while the table for the GO results doesn't show up at all.

When I checked some older reports, I noticed that this problem started to occur after I reinstalled the pipeline in June, which also update the used R version from 3.4 to 3.5. The most susceptible packages that were update with the reinstallation of the pipeline (which was still at v0.0.3 at that point), are:
- base R 3.4.3 -> 3.5
- rmarkdown 1.9 -> 1.10
- htmlwidgets 1.1 -> 1.2

I currently have troubles uploading the full sessionInfo output from the reports form the oldest report, where it still worked (pigx 0.0.3, R 3.4.3) and the earliest one where it didn't (pigx 0.0.3, R 3.5), but I can provide them otherwise if necessary.

**Comment by borauyar** [comment]
Hi Nicolai, Did you install the pipeline via Guix? If so, could you please tell me the version of pigx and also the version of rnaseq pipeline?

**Comment by rekado** [comment]
Alternatively, please just tell us the version of Guix you used to install it.

**Comment by Nicolai-vKuegelgen** [comment]
Okay, I apparently completely forgot about both checking back in here and the issue for quite a while - sorry about that.

I have now found another issue with the markdown script (which may or may not be related), but first to your questions:

- yes, the pipeline is installed via guix. With rnaseq 0.0.3  and pigx 0.0.2 I had both working reports (using R3.4.3) and non-working ones (R3.5.0). With the newest versions (pigx 0.0.3/rnaseq 0.0.4) I only have the combination with R3.5.0 and no working plots.

- the guix version I am currently using (updated yesterday) is:
 guix package (GNU Guix) 76d520facb54f4f86977683fd21bf1d4ac5ba45d
I have run the pipeline both from an isolated enviroment (only binaries from /gnu/var/guix/profiles/custom/chekulaeva/.guix-profile) and from an additional installation which had pigx on top of our 'usual' guix enviroment (pigx from /clusterhome/nkuegel/profiles/.guix-profile-pigx [that's the only package in that profile] while also having /gnu/var/guix/profiles/custom/chekulaevalab/.guix-profile active) - I don't get these plots with this version.

I have now dug into git logs & the dates of the /gnu/var/guix/profiles/custom/chekulaeva/.guix-profile-XX-link generations and tested some of the older profile generations. It looks like the last profile with which it still worked is:

/gnu/var/guix/profiles/custom/chekulaeva/.guix-profile-7-link 
 which links to  /gnu/store/zys8mc10vsfz29bv2n3isp6akx90j6kn-profile  (I'm not sure how to get a version number/hash for that profile generation) 




Now to another problem I encountered:

The pdf files that are created in addition to html-report are - at least for me - empty. There is definitely something written in the files, since they have different sizes, but I only get a blank white page when I look at it. (Again this happens with both of the environments described above).
I have played around with this problem a bit since I have another snakemake pipeline is build up very similar to pigx, but not directly installed through guix (meaning I directly installed R from guix), that behaves the same way: if I try to created pdf files *from within Rmarkdown* they show up blank.
I couldn't figure why this happens (so maybe its related to the plots in the html not showing up), but I did find a solution: saving the files with the cairo_pdf device instead of pdf works for me.

**Comment by Nicolai-vKuegelgen** [comment]
Just an update on this: newer versions of the pipeline (0.0.10 maybe also earlier) don't have this issue anymore. This may also be due to additional updates of some R packages, which I haven't checked specifically (either way installing everything from guix is no problem now).
