### ISSUE TITLE
Output nice errors when settings files are not defined

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/pigx_rnaseq#50]
Wen settings files are not defined the pipeline crashes with uninformative error

**Comment by borauyar** [comment]
@frenkiboy do you mean the locations section in the settings? There is a check for all locations in the validate_input.py script. See here: https://github.com/BIMSBbioinfo/pigx_rnaseq/blob/cc9d6719b1561b8d3d5c7caa1b40840020b58d73/scripts/validate_input.py#L23

**Comment by borauyar** [comment]
I can't reproduce this error. When settings.yaml is not provided, the pipeline fails with a message:
```
usage: pigx-rnaseq [-h] [-v] (--init [{settings,sample-sheet,both}] | -s SETTINGS) [-c CONFIGFILE] [--target TARGET] [-n] [--graph GRAPH] [--force] [--reason] [--unlock] [--verbose] [--printshellcmds] [--snakemake SNAKEMAKE] [sample_sheet]
pigx-rnaseq: error: one of the arguments --init -s/--settings is required
```
