### ISSUE TITLE
export bigwig files rather than bedgraph files

### ISSUE THREAD

**Issue by borauyar** [BIMSBbioinfo/pigx_rnaseq#54]
The pipeline currently produces bedgraph files for coverage tracks but it is not an ideal solution. It is better to produce bigwig files which are lightweight and also removes dependency on bedtools.

**Comment by frenkiboy** [comment]
I've already made this change in my local repo - will commit this week.

**Comment by borauyar** [comment]
Sorry I forgot abou that. I already did this. I am about to make a new release. So please wait :)
