### ISSUE TITLE
(dist)clean cleans files in release and/or git

### ISSUE THREAD

**Issue by smoe** [BIMSBbioinfo/pigx_rnaseq#60]
Hello,
These files
```
Makefile.in
build-aux/missing
build-aux/test-driver
```
are gone after the cleaning. This seems just right and I suggest to remove them from your releases. The files in build-aux are still under git source control and should likely also be removed.

Cheers,
Steffen

**Comment by rekado** [comment]
Hi Steffen,

> ```
> Makefile.in
> build-aux/missing
> build-aux/test-driver
> ```

They should not have been committed, but they will still be part of the
bootstrapped release tarballs.

-- 
Ricardo
