### ISSUE TITLE
norm_counts_deseq fails if samplesheet is edited

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [BIMSBbioinfo/pigx_rnaseq#63]
The norm_counts_deseq rule takes raw counts from STAR for all samples and then runs deseq normalisation on it and therefore is dependent on the ColData file (which gets updated when the samplesheet is edited).

However the collate_read_counts rule, which generates the input file for norm_counts_deseq is not dependend on the ColData file and will always use all count files in the directory, meaning that removal of sample from the samplehseet does not remove them from the 'counts_from_star.tsv' file (which means there is a difference between the samples in the count file and the samples in colData when norm_counts_deseq is run)

This can be fixed either by making collate_read_counts read the colData file and only use the samples specified there (or by making norm_counts_deseq do the same thing).

**Comment by borauyar** [comment]
https://github.com/BIMSBbioinfo/pigx_rnaseq/issues/56
