### ISSUE TITLE
stranded paired end data lead to unstranded bigWig files 

### ISSUE THREAD

**Issue by constadakis** [BIMSBbioinfo/pigx_rnaseq#69]
Hi all, 

we use paired end fastq files from stranded  libraries and get erroneous bigWig files from pigx-rnaseq.
the visualized tracks are not stranded. 
the bam files though seem to be correct. using samtools and deeptools on them allows for the generation of correct looking bigWig files. 

best, 
Konsta

**Comment by borauyar** [comment]
@constadakis I updated the pipeline to use deepTools bamCoverage for creating bigwig files (will be available from version 0.0.16).
