### ISSUE TITLE
Replace trimgalore with bbtrim

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/pigx_rnaseq#89]
Trimgalore should be replaced with a lightweight trimming tool - bbtrim
https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/bbduk-guide/

**Comment by borauyar** [comment]
https://github.com/BIMSBbioinfo/pigx_rnaseq/issues/95

**Comment by borauyar** [comment]
trim galore + fastqc are replaced with fastp in release v0.0.13
https://github.com/BIMSBbioinfo/pigx_rnaseq/releases/tag/v0.0.13
