### ISSUE TITLE
replace export.bw with a better candidate

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/pigx_rnaseq#91]
Candidates: 
1. bam2bw
https://github.com/cancerit/cgpBigWig

2. wiggleTools - samtools view test/bam.bam | wiggletools sam -
https://github.com/Ensembl/WiggleTools
don't know the exact command for conversion, but should be possible

3. megadepth - I would use this one because of the name
This one has both memory and time, and it beats rtracklayer by a lot
https://github.com/LieberInstitute/megadepth

4. deeptools is an option
http://deeptools.readthedocs.io/en/latest/content/tools/bamCoverage.html

I don't know how these tools scale with data (memory and cpu)

**Comment by borauyar** [comment]
https://github.com/BIMSBbioinfo/pigx_rnaseq/issues/69#issue-548917030

**Comment by borauyar** [comment]
Replaced export.bw with deeptools-bamCoverage in version 0.0.15 
see: https://github.com/BIMSBbioinfo/pigx_rnaseq/commit/f9660de48b3eb6ca48990717db9224c72b9c20ba
