### ISSUE TITLE
RNA-Seq pipeline stopping after trim galore

### ISSUE THREAD

**Issue by kerimsecener** [BIMSBbioinfo/pigx_rnaseq#95]
Hello,

I'm running pigx-rnaseq on three samples (paired-end):
trim_galore log files seem fine to me, however in the snakejob log files I see this:

_mv: cannot stat ‘/fast/CF_Sequencing/work_dir/cfische/SP005/bulk_RNA_seq/pigx_work/pigx_output/trimmed_reads/GYWU-1219_EIA5_CTNNB1_R1.good.fq.gz’: No such file or directory_

"_GYWU-1219_EIA5_CTNNB1_R1.good.fq.gz_ " is supposed to be the original fastq file name, I don't understand why the algorithm looks for it in the trimmed_reads folder ?

I'm attaching the yaml file, sample sheet, as well as error files.
[settings.yaml.txt](https://github.com/BIMSBbioinfo/pigx_rnaseq/files/6522751/settings.yaml.txt)
[trim_galore_GYWU_1219.log](https://github.com/BIMSBbioinfo/pigx_rnaseq/files/6522753/trim_galore_GYWU_1219.log)
[snakejob.trim_galore_pe.7.sh.e4460475.txt](https://github.com/BIMSBbioinfo/pigx_rnaseq/files/6522757/snakejob.trim_galore_pe.7.sh.e4460475.txt)
[sample_sheet.csv](https://github.com/BIMSBbioinfo/pigx_rnaseq/files/6522758/sample_sheet.csv)

Thanks,

Kerim

**Comment by borauyar** [comment]
Hi Kerim, 
I made a new release replacing trim galore with a faster/better alternative. 
https://github.com/BIMSBbioinfo/pigx_rnaseq/releases/tag/v0.0.13

The guix package for this release should be available within a couple of days.
Best,
Bora
